### ISSUE TITLE
Fault in Gem

### ISSUE THREAD

**Issue by vanvictor20** [Anslem27/gem-music#20]
When playing  music, there reaches a point where it starts re-echoing what had already played with the song still continuing.

**Comment by kolynzb** [comment]
@vanvictor20  could you attach screenshots

**Comment by vanvictor20** [comment]
There no screen shots it's more in the time of play

**Comment by Anslem27** [comment]
> There no screen shots it's more in the time of play

Well that's one weird explanation. But let me see what I can do by the end of today

**Comment by Anslem27** [comment]
> There no screen shots it's more in the time of play

Try this build. https://github.com/Anslem27/Gem/releases/tag/Fixes

**Comment by Anslem27** [comment]
> @vanvictor20 could you attach screenshots

Speaking of screenshots, i have added screenshots in the assets folder for the readme
